on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
      
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    

    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'nginx'
        namespace: 'default'
        chart: 'demochart'
        token: '${{ github.token }}'
        values: |
          name: foobar
        value-files: >-
          [
            "values.yaml" 
          ]
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
